/* Copyright 2026 Anton Tananaev (anton@traccar.org) */
package org.traccar.mobile;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.traccar.model.Device;
import org.traccar.storage.Storage;

import javax.sql.DataSource;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileTime;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Alertas del panel admin: clasificación pura, consultas contra H2 real
 * (mismo esquema que usa el server) y lectura best-effort del filesystem.
 */
public class AdminAlertsServiceTest {

    private static final long DEVICE_ID = 7L;

    private DataSource dataSource;
    private AdminAlertsService service;
    private MobileJourneyRegistry registry;
    private Path tempDir;
    private Path watchdogLog;
    private final List<Device> devices = new ArrayList<>();

    @BeforeEach
    public void setUp() throws Exception {
        JdbcDataSource h2 = new JdbcDataSource();
        h2.setURL("jdbc:h2:mem:alerts" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource = h2;
        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE tc_devices (id bigint primary key, name varchar(128), "
                    + "uniqueid varchar(128), lastupdate timestamp)");
            statement.execute("CREATE TABLE tc_device_health (id bigint generated by default as identity "
                    + "primary key, deviceid bigint not null, ts timestamp not null, "
                    + "eventtype varchar(32), reason varchar(64))");
            statement.execute("CREATE TABLE tc_recovery_event (id bigint generated by default as identity "
                    + "primary key, deviceid bigint not null, ts timestamp not null, "
                    + "eventtype varchar(32), reason varchar(64))");
        }

        Storage storage = mock(Storage.class);
        when(storage.getObjects(eq(Device.class), any())).thenAnswer(invocation -> devices);
        registry = new MobileJourneyRegistry(storage);

        tempDir = Files.createTempDirectory("dmj-alerts");
        watchdogLog = tempDir.resolve("watchdog.log");
        service = new AdminAlertsService(dataSource, storage, registry, tempDir, watchdogLog);
    }

    private void insertHealth(long deviceId, long ts, String eventType, String reason) throws Exception {
        try (Connection connection = dataSource.getConnection();
                PreparedStatement statement = connection.prepareStatement(
                        "INSERT INTO tc_device_health (deviceid, ts, eventtype, reason) VALUES (?, ?, ?, ?)")) {
            statement.setLong(1, deviceId);
            statement.setTimestamp(2, new Timestamp(ts));
            statement.setString(3, eventType);
            statement.setString(4, reason);
            statement.executeUpdate();
        }
    }

    private void insertRecovery(long deviceId, long ts, String eventType, String reason) throws Exception {
        try (Connection connection = dataSource.getConnection();
                PreparedStatement statement = connection.prepareStatement(
                        "INSERT INTO tc_recovery_event (deviceid, ts, eventtype, reason) VALUES (?, ?, ?, ?)")) {
            statement.setLong(1, deviceId);
            statement.setTimestamp(2, new Timestamp(ts));
            statement.setString(3, eventType);
            statement.setString(4, reason);
            statement.executeUpdate();
        }
    }

    private void insertDevice(long id, String name) throws Exception {
        try (Connection connection = dataSource.getConnection();
                PreparedStatement statement = connection.prepareStatement(
                        "INSERT INTO tc_devices (id, name, uniqueid, lastupdate) VALUES (?, ?, ?, ?)")) {
            statement.setLong(1, id);
            statement.setString(2, name);
            statement.setString(3, "uid-" + id);
            statement.setTimestamp(4, new Timestamp(System.currentTimeMillis()));
            statement.executeUpdate();
        }
    }

    private Device device(String name, long lastUpdateMs) {
        Device device = new Device();
        device.setId(DEVICE_ID);
        device.setName(name);
        device.setUniqueId("uid-" + DEVICE_ID);
        if (lastUpdateMs > 0) {
            device.setLastUpdate(new Date(lastUpdateMs));
        }
        return device;
    }

    private static List<AdminAlertsService.Alert> byCategory(
            AdminAlertsService.AlertsReport report, String category) {
        return report.alerts().stream().filter(alert -> category.equals(alert.category())).toList();
    }

    @Test
    public void testClassification() {
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL,
                AdminAlertsService.classifyHealthEvent("PROCESS_FREEZE_DETECTED"));
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL,
                AdminAlertsService.classifyHealthEvent("CRITICAL"));
        assertNull(AdminAlertsService.classifyHealthEvent("HEARTBEAT"));

        assertEquals(AdminAlertsService.SEVERITY_CRITICAL,
                AdminAlertsService.classifyRecoveryEvent("RECOVERY_BLOCKED"));
        assertEquals(AdminAlertsService.SEVERITY_WARNING,
                AdminAlertsService.classifyRecoveryEvent("RECOVERY_TIMEOUT"));
        assertNull(AdminAlertsService.classifyRecoveryEvent("RECOVERY_SENT"));
    }

    @Test
    public void testSilenceThresholds() {
        long now = System.currentTimeMillis();
        assertNull(AdminAlertsService.silenceAlert("Camión 1", DEVICE_ID, 0L, now));
        assertNull(AdminAlertsService.silenceAlert("Camión 1", DEVICE_ID, now - 9 * 60_000L, now));
        AdminAlertsService.Alert warning = AdminAlertsService.silenceAlert(
                "Camión 1", DEVICE_ID, now - 11 * 60_000L, now);
        assertNotNull(warning);
        assertEquals(AdminAlertsService.SEVERITY_WARNING, warning.severity());
        assertTrue(warning.message().contains("11 min"));
        AdminAlertsService.Alert critical = AdminAlertsService.silenceAlert(
                "Camión 1", DEVICE_ID, now - 45 * 60_000L, now);
        assertNotNull(critical);
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL, critical.severity());
    }

    @Test
    public void testCollectFindsSilentActiveJourney() {
        long now = System.currentTimeMillis();
        Device silent = device("Camión 1", now - 12 * 60_000L);
        Device fresh = device("Camión 2", now - 60_000L);
        fresh.setId(DEVICE_ID + 1);
        devices.add(silent);
        devices.add(fresh);
        registry.start(silent.getId(), 41L);
        registry.start(fresh.getId(), 42L);

        List<AdminAlertsService.Alert> alerts = byCategory(
                service.collect(), AdminAlertsService.CATEGORY_JOURNEY_SILENCE);
        assertEquals(1, alerts.size());
        assertEquals("Camión 1", alerts.get(0).deviceName());
        assertEquals(AdminAlertsService.SEVERITY_WARNING, alerts.get(0).severity());
    }

    @Test
    public void testCollectUsesPresenceAttributeForSilence() {
        long now = System.currentTimeMillis();
        Device device = device("Camión 1", 0L);
        device.getAttributes().put(MobilePresenceTracker.ATTR_LAST_PRESENCE_AT,
                Long.toString(now - 40 * 60_000L));
        devices.add(device);
        registry.start(device.getId(), 41L);

        List<AdminAlertsService.Alert> alerts = byCategory(
                service.collect(), AdminAlertsService.CATEGORY_JOURNEY_SILENCE);
        assertEquals(1, alerts.size());
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL, alerts.get(0).severity());
    }

    @Test
    public void testHealthAlertsOnlyCriticalWithinWindow() throws Exception {
        long now = System.currentTimeMillis();
        insertDevice(DEVICE_ID, "Camión 1");
        insertHealth(DEVICE_ID, now - 60_000L, "PROCESS_FREEZE_DETECTED", "ANR_DEVICE");
        insertHealth(DEVICE_ID, now - 120_000L, "CRITICAL", "THERMAL");
        insertHealth(DEVICE_ID, now - 180_000L, "HEARTBEAT", null);
        insertHealth(DEVICE_ID, now - 48 * 3_600_000L, "CRITICAL", "OLD");

        List<AdminAlertsService.Alert> alerts = byCategory(
                service.collect(), AdminAlertsService.CATEGORY_DEVICE_HEALTH);
        assertEquals(2, alerts.size());
        assertTrue(alerts.stream().allMatch(a -> AdminAlertsService.SEVERITY_CRITICAL.equals(a.severity())));
        assertTrue(alerts.stream().anyMatch(a -> a.message().contains("Congelamiento")));
        assertTrue(alerts.stream().anyMatch(a -> a.message().contains("motivo: THERMAL")));
        assertEquals("Camión 1", alerts.get(0).deviceName());
    }

    @Test
    public void testRecoveryAlertsSeverityAndWindow() throws Exception {
        long now = System.currentTimeMillis();
        insertDevice(DEVICE_ID, "Camión 1");
        insertRecovery(DEVICE_ID, now - 60_000L, "RECOVERY_BLOCKED", "BLOCKED_INVALID_TOKEN");
        insertRecovery(DEVICE_ID, now - 120_000L, "RECOVERY_TIMEOUT", "TIMEOUT_NO_GPS");
        insertRecovery(DEVICE_ID, now - 180_000L, "RECOVERY_SENT", null);
        insertRecovery(DEVICE_ID, now - 30 * 3_600_000L, "RECOVERY_BLOCKED", "OLD");

        List<AdminAlertsService.Alert> alerts = byCategory(
                service.collect(), AdminAlertsService.CATEGORY_RECOVERY);
        assertEquals(2, alerts.size());
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL, alerts.get(0).severity());
        assertEquals(AdminAlertsService.SEVERITY_WARNING, alerts.get(1).severity());
        assertTrue(alerts.get(1).message().contains("TIMEOUT_NO_GPS"));
    }

    @Test
    public void testBackupStatusPicksNewestFile() throws Exception {
        long now = System.currentTimeMillis();
        Path old = Files.writeString(tempDir.resolve("traccar-old.dump"), "old");
        Path fresh = Files.writeString(tempDir.resolve("traccar-new.dump"), "fresh-dump");
        Files.setLastModifiedTime(old, FileTime.fromMillis(now - 48 * 3_600_000L));
        Files.setLastModifiedTime(fresh, FileTime.fromMillis(now - 30 * 3_600_000L));

        AdminAlertsService.BackupStatus backup = AdminAlertsService.backupStatus(tempDir, now);
        assertTrue(backup.available());
        assertEquals(fresh.toString(), backup.path());
        assertEquals(10L, backup.sizeBytes());
        assertEquals(30L, backup.ageHours());

        AdminAlertsService.AlertsReport report = service.collect();
        assertEquals(1, byCategory(report, AdminAlertsService.CATEGORY_BACKUP).size());
        assertEquals(AdminAlertsService.SEVERITY_WARNING,
                byCategory(report, AdminAlertsService.CATEGORY_BACKUP).get(0).severity());
    }

    @Test
    public void testBackupMissingAndStaleSeverities() {
        long now = System.currentTimeMillis();
        AdminAlertsService.BackupStatus missing = AdminAlertsService.backupStatus(
                tempDir.resolve("does-not-exist"), now);
        assertFalse(missing.available());
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL,
                AdminAlertsService.backupAlert(missing, now).severity());

        AdminAlertsService.BackupStatus stale = new AdminAlertsService.BackupStatus(
                "/var/backups/dmj/dump", true, now - 40 * 3_600_000L, 10L, 40L);
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL,
                AdminAlertsService.backupAlert(stale, now).severity());

        AdminAlertsService.BackupStatus healthy = new AdminAlertsService.BackupStatus(
                "/var/backups/dmj/dump", true, now, 10L, 2L);
        assertNull(AdminAlertsService.backupAlert(healthy, now));
    }

    @Test
    public void testDiskThresholds() {
        long now = System.currentTimeMillis();
        AdminAlertsService.DiskStatus ok = new AdminAlertsService.DiskStatus(
                "/", true, 100L, 40L, 60);
        assertNull(AdminAlertsService.diskAlert(ok, now));

        AdminAlertsService.DiskStatus warning = new AdminAlertsService.DiskStatus(
                "/", true, 100L, 20L, 80);
        assertEquals(AdminAlertsService.SEVERITY_WARNING,
                AdminAlertsService.diskAlert(warning, now).severity());

        AdminAlertsService.DiskStatus critical = new AdminAlertsService.DiskStatus(
                "/", true, 100L, 5L, 95);
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL,
                AdminAlertsService.diskAlert(critical, now).severity());
    }

    @Test
    public void testDiskStatusAvailableInCurrentEnvironment() {
        AdminAlertsService.DiskStatus disk = AdminAlertsService.diskStatus(tempDir);
        assertTrue(disk.available());
        assertNotNull(disk.usedPercent());
        assertTrue(disk.usedPercent() >= 0 && disk.usedPercent() <= 100);
    }

    @Test
    public void testWatchdogTailAndAlert() throws Exception {
        long now = System.currentTimeMillis();
        Files.writeString(watchdogLog, String.join("\n",
                "2026-09-19 10:00:00 watchdog: ok (HTTP 200)",
                "2026-09-19 10:01:00 watchdog: ok (HTTP 200)",
                "2026-09-19 10:02:00 watchdog: sin respuesta del servidor (code=000); reinicio dmj-traccar.service",
                "2026-09-19 10:03:00 watchdog: ok (HTTP 200)") + "\n");
        Files.setLastModifiedTime(watchdogLog, FileTime.fromMillis(now));

        AdminAlertsService.WatchdogStatus status = AdminAlertsService.watchdogStatus(watchdogLog);
        assertTrue(status.available());
        assertEquals(4, status.lines().size());
        assertNull(AdminAlertsService.watchdogAlert(status, now));
        assertEquals("2026-09-19 10:03:00 watchdog: ok (HTTP 200)", status.lines().get(3));

        AdminAlertsService.WatchdogStatus missing = AdminAlertsService.watchdogStatus(
                tempDir.resolve("missing-watchdog.log"));
        assertFalse(missing.available());
        assertNull(missing.lines());
        assertNull(AdminAlertsService.watchdogAlert(missing, now));
    }

    @Test
    public void testWatchdogRestartGeneratesWarning() throws Exception {
        long now = System.currentTimeMillis();
        Files.writeString(watchdogLog, "2026-09-19 10:02:00 watchdog: sin respuesta del servidor "
                + "(code=000); reinicio dmj-traccar.service\n");
        Files.setLastModifiedTime(watchdogLog, FileTime.fromMillis(now));

        AdminAlertsService.AlertsReport report = service.collect();
        List<AdminAlertsService.Alert> alerts = byCategory(report, AdminAlertsService.CATEGORY_WATCHDOG);
        assertEquals(1, alerts.size());
        assertEquals(AdminAlertsService.SEVERITY_WARNING, alerts.get(0).severity());
        assertTrue(alerts.get(0).message().contains("reinició"));
    }

    @Test
    public void testReadLastLinesKeepsOnlyTail() throws Exception {
        Path log = tempDir.resolve("tail.log");
        StringBuilder content = new StringBuilder();
        for (int index = 0; index < 100; index++) {
            content.append("line-").append(index).append('\n');
        }
        Files.writeString(log, content.toString());
        List<String> lines = AdminAlertsService.readLastLines(log, 3);
        assertEquals(List.of("line-97", "line-98", "line-99"), lines);
    }

    @Test
    public void testFunnelAlertThresholds() {
        long now = 1_800_000_000_000L;
        assertNull(AdminAlertsService.funnelAlert(
                "Camión 1", DEVICE_ID, now - 23 * 3_600_000L, "1.1.22", now));
        AdminAlertsService.Alert never = AdminAlertsService.funnelAlert(
                "Camión 1", DEVICE_ID, null, "1.1.22", now);
        assertNotNull(never);
        assertEquals(AdminAlertsService.SEVERITY_WARNING, never.severity());
        assertEquals(AdminAlertsService.CATEGORY_HEALTH_FUNNEL, never.category());
        assertEquals(DEVICE_ID, never.deviceId());
        AdminAlertsService.Alert warning = AdminAlertsService.funnelAlert(
                "Camión 1", DEVICE_ID, now - 25 * 3_600_000L, "1.1.22", now);
        assertNotNull(warning);
        assertEquals(AdminAlertsService.SEVERITY_WARNING, warning.severity());
        assertTrue(warning.message().contains("25 h"));
        AdminAlertsService.Alert critical = AdminAlertsService.funnelAlert(
                "Camión 1", DEVICE_ID, now - 50 * 3_600_000L, "1.1.22", now);
        assertNotNull(critical);
        assertEquals(AdminAlertsService.SEVERITY_CRITICAL, critical.severity());
    }

    @Test
    public void testFunnelAlertSkipsVersionsWithoutFunnel() {
        long now = 1_800_000_000_000L;
        // Pre-F0 (1.1.20): nunca envió embudo → no es alerta, es esperado.
        assertNull(AdminAlertsService.funnelAlert("Camión 1", DEVICE_ID, null, "1.1.20", now));
        assertNull(AdminAlertsService.funnelAlert("Camión 1", DEVICE_ID, null, null, now));
        assertNull(AdminAlertsService.funnelAlert("Camión 1", DEVICE_ID, null, "", now));
        // Regresión: aunque la versión sea vieja, si envió y dejó de enviar, alerta.
        assertNotNull(AdminAlertsService.funnelAlert(
                "Camión 1", DEVICE_ID, now - 30 * 3_600_000L, "1.1.20", now));
    }

    @Test
    public void testIsNativeClient() {
        // Sin atributo (equipos viejos) o blank: nativo → embudo esperado.
        assertTrue(AdminAlertsService.isNativeClient(null));
        assertTrue(AdminAlertsService.isNativeClient(Map.of()));
        assertTrue(AdminAlertsService.isNativeClient(Map.of(AdminAlertsService.ATTR_MOBILE_CLIENT, "")));
        assertTrue(AdminAlertsService.isNativeClient(Map.of(AdminAlertsService.ATTR_MOBILE_CLIENT, "  ")));
        Map<String, Object> nullValue = new HashMap<>();
        nullValue.put(AdminAlertsService.ATTR_MOBILE_CLIENT, null);
        assertTrue(AdminAlertsService.isNativeClient(nullValue));
        assertTrue(AdminAlertsService.isNativeClient(
                Map.of(AdminAlertsService.ATTR_MOBILE_CLIENT, "dmujeres-native")));
        assertTrue(AdminAlertsService.isNativeClient(
                Map.of(AdminAlertsService.ATTR_MOBILE_CLIENT, " dmujeres-native ")));
        // App de respaldo u otro cliente: no envía embudo → no se alerta.
        assertFalse(AdminAlertsService.isNativeClient(
                Map.of(AdminAlertsService.ATTR_MOBILE_CLIENT, "dmujeres-traccar")));
        assertFalse(AdminAlertsService.isNativeClient(
                Map.of(AdminAlertsService.ATTR_MOBILE_CLIENT, "otro")));
    }

    @Test
    public void testSupportsFunnelVersionCompare() {
        assertTrue(AdminAlertsService.supportsFunnel("1.1.22"));
        assertTrue(AdminAlertsService.supportsFunnel("1.1.23"));
        assertTrue(AdminAlertsService.supportsFunnel("1.2.0"));
        assertTrue(AdminAlertsService.supportsFunnel("2.0"));
        assertFalse(AdminAlertsService.supportsFunnel("1.1.21"));
        assertFalse(AdminAlertsService.supportsFunnel("1.1.9"));
        assertFalse(AdminAlertsService.supportsFunnel("1.0.99"));
        assertFalse(AdminAlertsService.supportsFunnel("basura"));
    }

    @Test
    public void testReportSystemStatusIncludesServerStart() {
        AdminAlertsService.AlertsReport report = service.collect();
        assertTrue(report.system().serverStartedAt() > 0L);
        assertTrue(report.system().uptimeSeconds() >= 0L);
        assertNotNull(report.system().disk());
        assertEquals(report.alerts().size(), report.total());
        assertTrue(AdminAlertsService.severityRank(report.alerts().isEmpty()
                ? AdminAlertsService.SEVERITY_INFO : report.alerts().get(0).severity()) > 0);
    }
}
