/* Copyright 2026 Anton Tananaev (anton@traccar.org) */
package org.traccar.mobile;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.traccar.config.Config;

import javax.sql.DataSource;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * F2: la máquina completa de recovery contra una BD real (H2 PostgreSQL):
 * el servidor sólo declara SERVER_ACK/SUCCESS con posición real; el cliente
 * no puede fabricar la etapa SERVER_ACK; timeout desbloquea probes nuevos.
 */
public class FcmRecoveryServiceTest {

    private static final long DEVICE_ID = 48L;

    private DataSource dataSource;
    private Config config;
    private FcmSender sender;
    private FcmTokenStore tokens;
    private FcmRecoveryService service;

    @BeforeEach
    public void setUp() throws Exception {
        JdbcDataSource h2 = new JdbcDataSource();
        h2.setURL("jdbc:h2:mem:fcmrecovery" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource = h2;
        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE tc_recovery_event ("
                    + "id bigint generated by default as identity primary key, "
                    + "deviceid integer not null, ts timestamp not null, eventtype varchar(32) not null, "
                    + "reason varchar(32), attemptid varchar(64), status varchar(16), sessionid varchar(64), "
                    + "fcmmsgid varchar(128), fcmpriority varchar(16), source varchar(16))");
        }
        config = mock(Config.class);
        when(config.getBoolean(any())).thenReturn(true);
        when(config.getInteger(any())).thenReturn(300);
        sender = mock(FcmSender.class);
        when(sender.sendRecoveryProbe(any(), any(), any(), anyLong()))
                .thenReturn(new FcmSender.SendResult(FcmSender.Status.READY, "msg-1", null, false));
        tokens = mock(FcmTokenStore.class);
        when(tokens.activeToken(DEVICE_ID)).thenReturn("tok-test");
        service = new FcmRecoveryService(config, dataSource, sender, tokens);
    }

    @Test
    public void testSuccessRequiresRealPositionAfterFullClientChain() throws Exception {
        service.onSilenceDetected(DEVICE_ID, "qa-test", "silence-test");
        String attemptId = queryString("SELECT attemptid FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SENT'");
        assertNotNull(attemptId);
        verify(sender).sendRecoveryProbe(eq("tok-test"), eq(attemptId), eq("qa-test"), anyLong());

        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "RECOVERY_RECEIVED", "high", "delivered"));
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "STARTED", "high", "started"));
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "FGS_ACTIVE", "high", "fgs"));
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "TRACKING_ACTIVE", "high", "tracking"));
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "GPS_CONFIRMED", "high", "gps"));

        // Evidencia del cliente completa, pero sin posición real: NO hay SUCCESS.
        assertEquals(0, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SUCCESS'"));
        assertEquals(0, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SERVER_ACK'"));

        // Llega la posición real aceptada: el SERVIDOR fija SERVER_ACK → SUCCESS.
        service.onPositionAccepted(DEVICE_ID);
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event "
                + "WHERE eventtype = 'RECOVERY_SERVER_ACK' AND source = 'SERVER'"));
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SUCCESS'"));
    }

    @Test
    public void testClientCannotFabricateServerAck() throws Exception {
        service.onSilenceDetected(DEVICE_ID, "qa-test", "silence-test");
        String attemptId = queryString("SELECT attemptid FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SENT'");

        assertFalse(service.acknowledge(DEVICE_ID, attemptId, "SERVER_ACK", "high", "spoof"));
        assertFalse(service.acknowledge(DEVICE_ID, attemptId, "RECOVERY_SERVER_ACK", "high", "spoof-prefixed"));
        assertEquals(0, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'SERVER_ACK'"));
        assertEquals(2, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'RECOVERY_ACK_REJECTED'"));
    }

    @Test
    public void testUnknownStageIsRejectedAndAudited() throws Exception {
        service.onSilenceDetected(DEVICE_ID, "qa-test", "silence-test");
        String attemptId = queryString("SELECT attemptid FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SENT'");

        assertFalse(service.acknowledge(DEVICE_ID, attemptId, "TURBO_MODE", "high", "unknown"));
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event "
                + "WHERE eventtype = 'RECOVERY_ACK_REJECTED' AND reason = 'UNKNOWN_STAGE_TURBO_MODE'"));
    }

    @Test
    public void testLongClientValuesAreTruncatedNotLost() throws Exception {
        service.onSilenceDetected(DEVICE_ID, "qa-test", "silence-test");
        String longAttemptId = "fcm-" + "x".repeat(120);
        String longReason = "r".repeat(200);
        assertTrue(service.acknowledge(DEVICE_ID, longAttemptId, "RECEIVED", "high", longReason));
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'RECEIVED'"));
        assertEquals(64, queryInt("SELECT length(attemptid) FROM tc_recovery_event WHERE eventtype = 'RECEIVED'"));
        assertEquals(32, queryInt("SELECT length(reason) FROM tc_recovery_event WHERE eventtype = 'RECEIVED'"));
    }

    @Test
    public void testTimeoutUnblocksNewProbe() throws Exception {
        Timestamp old = new Timestamp(System.currentTimeMillis() - 600_000L);
        try (Connection connection = dataSource.getConnection();
                PreparedStatement statement = connection.prepareStatement(
                        "INSERT INTO tc_recovery_event (deviceid, ts, eventtype, attemptid, status, source) "
                                + "VALUES (?, ?, 'RECOVERY_SENT', 'fcm-old', 'PENDING', 'FCM')")) {
            statement.setLong(1, DEVICE_ID);
            statement.setTimestamp(2, old);
            statement.executeUpdate();
        }
        service.markTimeouts();
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event "
                + "WHERE eventtype = 'RECOVERY_TIMEOUT' AND reason = 'TIMEOUT_NO_DELIVERY'"));

        // Tras el TIMEOUT, el intento viejo ya no bloquea: se envía un probe nuevo.
        service.onSilenceDetected(DEVICE_ID, "qa-test", "silence-after-timeout");
        verify(sender).sendRecoveryProbe(any(), any(), eq("qa-test"), anyLong());
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event "
                + "WHERE eventtype = 'RECOVERY_SENT' AND attemptid <> 'fcm-old'"));
    }

    @Test
    public void testServerAckWithoutFullEvidenceTimesOutWithCause() throws Exception {
        service.onSilenceDetected(DEVICE_ID, "qa-test", "silence-test");
        String attemptId = queryString("SELECT attemptid FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SENT'");
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "RECEIVED", "high", "r"));
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "STARTED", "high", "r"));
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "FGS_ACTIVE", "high", "r"));
        assertTrue(service.acknowledge(DEVICE_ID, attemptId, "TRACKING_ACTIVE", "high", "r"));
        // Posición real → el servidor fija SERVER_ACK, pero GPS_CONFIRMED falta:
        // no hay SUCCESS y el intento debe terminar con causa, no quedar mudo.
        service.onPositionAccepted(DEVICE_ID);
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SERVER_ACK'"));
        assertEquals(0, queryInt("SELECT count(*) FROM tc_recovery_event WHERE eventtype = 'RECOVERY_SUCCESS'"));

        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            statement.executeUpdate("UPDATE tc_recovery_event SET ts = DATEADD('SECOND', -900, ts) "
                    + "WHERE eventtype = 'RECOVERY_SENT'");
        }
        service.markTimeouts();
        service.markTimeouts();
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event "
                + "WHERE eventtype = 'RECOVERY_TIMEOUT' AND reason = 'TIMEOUT_NO_GPS'"));
    }

    @Test
    public void testNoProbeWhenFeatureDisabled() throws Exception {
        when(config.getBoolean(any())).thenReturn(false);
        service.onSilenceDetected(DEVICE_ID, "qa-test", "silence-test");
        verify(sender, never()).sendRecoveryProbe(any(), any(), any(), anyLong());
        assertEquals(1, queryInt("SELECT count(*) FROM tc_recovery_event "
                + "WHERE eventtype = 'RECOVERY_SKIPPED_DISABLED'"));
    }

    private int queryInt(String sql) throws Exception {
        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getInt(1);
        }
    }

    private String queryString(String sql) throws Exception {
        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery(sql)) {
            return rs.next() ? rs.getString(1) : null;
        }
    }
}
