/* Copyright 2026 Anton Tananaev (anton@traccar.org) */
package org.traccar.mobile;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.traccar.session.cache.CacheManager;
import org.traccar.model.Device;
import org.traccar.storage.Storage;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * FASE 7: la salud móvil se persiste de forma idempotente por (deviceid, ts),
 * valida el contrato y deja el último estado en atributos sin tocar tracking.
 * Contra H2 real (misma tabla que Liquidbase crea en 6.14.4/6.14.6).
 */
public class MobileHealthServiceTest {

    private static final long DEVICE_ID = 49L;

    private DataSource dataSource;
    private MobileHealthService service;
    private Device device;
    private final ObjectMapper mapper = new ObjectMapper();

    @BeforeEach
    public void setUp() throws Exception {
        JdbcDataSource h2 = new JdbcDataSource();
        h2.setURL("jdbc:h2:mem:health" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource = h2;
        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE tc_device_health ("
                    + "id bigint generated by default as identity primary key, "
                    + "deviceid integer not null, ts timestamp not null, sessionid varchar(64), "
                    + "wallbucket bigint, elapsedms bigint, eventtype varchar(24), reason varchar(64), "
                    + "manufacturer varchar(64), model varchar(64), androidversion varchar(32), "
                    + "appversion varchar(32), healthstate varchar(16), fgs boolean, screenon boolean, "
                    + "motion varchar(16), network varchar(16), outbox integer, "
                    + "lastfixat timestamp, readiness varchar(16), continuity varchar(16), "
                    + "continuitycause varchar(32), recovery varchar(32), attributes clob, "
                    + "CONSTRAINT idx_device_health_unique UNIQUE (deviceid, ts))");
        }
        Storage storage = mock(Storage.class);
        CacheManager cacheManager = mock(CacheManager.class);
        service = new MobileHealthService(new JdbcDeviceHealthStore(dataSource), storage, mapper, cacheManager);
        device = new Device();
        device.setId(DEVICE_ID);
        device.setUniqueId("qa-f0");
        device.getAttributes().put("mobile.vendor", "ZTE");
        device.getAttributes().put("mobile.model", "Z2450");
    }

    private String payload(long ts, String event) {
        return "{\"device\":{\"manufacturer\":\"ZTE\",\"model\":\"Z2450\","
                + "\"androidVersion\":\"14\",\"androidSdk\":\"34\",\"rom\":\"MyOS 14\"},"
                + "\"snapshots\":[{"
                + "\"sessionId\":\"sess-1\",\"wallMs\":" + ts + ",\"wallBucket\":" + (ts / 60_000L)
                + ",\"elapsedMs\":120000,\"eventType\":\"" + event + "\",\"reason\":\"\","
                + "\"fgs\":true,\"motion\":\"STATIONARY\",\"network\":\"wifi\",\"outbox\":3,"
                + "\"healthState\":\"LIVE\"}]}";
    }

    @Test
    public void testIngestPersistsAndDeduplicates() throws Exception {
        long now = System.currentTimeMillis();
        MobileHealthService.Outcome first = service.ingest(device, payload(now, "HEARTBEAT"), now);
        assertEquals(1, first.accepted());
        assertEquals(0, first.duplicates());
        assertEquals(0, first.rejected());
        assertFalse(first.throttled());

        // Reenvío del mismo snapshot (reintento): duplicado, no error.
        MobileHealthService.Outcome second = service.ingest(device, payload(now, "HEARTBEAT"), now + 20_000L);
        assertEquals(0, second.accepted());
        assertEquals(1, second.duplicates());

        try (Connection connection = dataSource.getConnection();
                PreparedStatement statement = connection.prepareStatement(
                        "SELECT COUNT(*), MAX(healthstate), MAX(manufacturer), MAX(sessionid) FROM tc_device_health")) {
            try (ResultSet rs = statement.executeQuery()) {
                assertTrue(rs.next());
                assertEquals(1, rs.getInt(1));
                assertEquals("LIVE", rs.getString(2));
                assertEquals("ZTE", rs.getString(3));
                assertEquals("sess-1", rs.getString(4));
            }
        }
    }

    @Test
    public void testAttributesUpdatedWithLatestStateAndProfile() throws Exception {
        long now = System.currentTimeMillis();
        service.ingest(device, payload(now, "HEARTBEAT"), now);
        assertEquals("LIVE", device.getAttributes().get("mobile.healthState"));
        assertEquals(now, device.getAttributes().get("mobile.healthAt"));
        assertEquals("14", device.getAttributes().get("mobile.androidVersion"));
        assertEquals("34", device.getAttributes().get("mobile.androidSdk"));
        assertEquals("MyOS 14", device.getAttributes().get("mobile.rom"));
        assertEquals(3, device.getAttributes().get("mobile.healthOutbox"));
    }

    @Test
    public void testRejectsInvalidItemsAndHonorsThrottle() throws Exception {
        long now = System.currentTimeMillis();
        String badEvent = payload(now, "HACK").replace("\"HACK\"", "\"NOT_AN_EVENT\"");
        MobileHealthService.Outcome rejected = service.ingest(device, badEvent, now);
        assertEquals(0, rejected.accepted());
        assertEquals(1, rejected.rejected());

        // Timestamp futuro irreal: rechazado.
        String future = payload(now + 3_600_000L, "HEARTBEAT");
        assertEquals(1, service.ingest(device, future, now).rejected());

        // Throttle: el mismo device en <10 s no procesa.
        service.ingest(device, payload(now, "HEARTBEAT"), now + 30_000L);
        MobileHealthService.Outcome throttled = service.ingest(device, payload(now + 60_000L, "HEARTBEAT"), now + 31_000L);
        assertTrue(throttled.throttled());

        // deviceId del body inconsistente: rechazado.
        String mismatch = payload(now + 120_000L, "HEARTBEAT")
                .replace("\"healthState\":\"LIVE\"", "\"healthState\":\"LIVE\",\"deviceId\":999");
        assertEquals(1, service.ingest(device, mismatch, now + 60_000L).rejected());
    }

    @Test
    public void testEmptyOrTooManyItemsRejected() throws Exception {
        long now = System.currentTimeMillis();
        assertEquals(0, service.ingest(device, "{\"snapshots\":[]}", now).accepted());
        assertEquals(0, service.ingest(device, "not-json", now).accepted());
        StringBuilder many = new StringBuilder("{\"snapshots\":[");
        for (int i = 0; i < MobileHealthService.MAX_ITEMS + 1; i++) {
            if (i > 0) {
                many.append(',');
            }
            many.append("{\"wallMs\":").append(now + i).append(",\"eventType\":\"HEARTBEAT\"}");
        }
        many.append("]}");
        assertEquals(0, service.ingest(device, many.toString(), now).accepted());
    }

    @Test
    public void testParseAcceptsWhitelistedMotionAndDropsGarbage() {
        long now = System.currentTimeMillis();
        com.fasterxml.jackson.databind.JsonNode item = mapper.createObjectNode()
                .put("wallMs", now)
                .put("eventType", "HEARTBEAT")
                .put("motion", "DANCING")
                .put("network", "carrier-pigeon")
                .put("outbox", -5);
        DeviceHealthStore.Snapshot snapshot = service.parse(DEVICE_ID, item, now, "LIVE");
        assertNotNull(snapshot);
        assertNull(snapshot.motion());
        assertNull(snapshot.network());
        assertEquals(0, snapshot.outbox());
    }

    @Test
    void funnelAceptaJsonCompactoYRechazaBasura() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        assertEquals("{\"rx\":1}",
                MobileHealthService.funnelOf(mapper.readTree("{\"funnel\":\"{\\\"rx\\\":1}\"}")));
        assertNull(MobileHealthService.funnelOf(mapper.readTree("{\"funnel\":\"\"}")));
        assertNull(MobileHealthService.funnelOf(mapper.readTree("{\"funnel\":\"no-json\"}")));
        assertNull(MobileHealthService.funnelOf(mapper.readTree("{\"funnel\":123}")));
        assertNull(MobileHealthService.funnelOf(
                mapper.readTree("{\"funnel\":\"{" + "x".repeat(600) + "}\"}")));
    }
}
